### ISSUE TITLE
Configuration error (auto update)

### ISSUE THREAD

**Issue by maeb3** [disaster123/ioBroker.signifylights#16]
Wenn in der Instanz-Konfiguration die Felder für "udp target ip for auto update" und "udp mac adress for auto update" nicht gefüllt sind, wirft der Adapter beim Starten den Fehler "adapter is unconfigured". Das ist grundsätzlich OK, allerdings kommt der Fehler auch, wenn die CheckBox "register devices for Auto update" gar nicht aktiviert ist. 

Meines Erachtens sollte die Plausibilisierung der Adapter-Konfig diese beiden Felder nur prüfen, wenn auch "register devices for Auto update" aktiviert ist (in main.js --> async onReady() ).

**Comment by disaster123** [comment]
@maeb3 bitte einmal den aktuellen main branch testen. Vielen Dank für den Hinweis.

**Comment by disaster123** [comment]
@maeb3 getestet?

**Comment by maeb3** [comment]
Ja, issue kann geschlossen werden.

**Comment by disaster123** [comment]
thx - kommt dann 0.2.1
