### ISSUE TITLE
Is it possible to add SMART BULB Edisson ST64?

### ISSUE THREAD

**Issue by Burgruine** [disaster123/ioBroker.signifylights#42]
Hallo, 
ist it possible to add WIZ Wi-Fi BLE ST64 E27 822-65 RGB CL?
moduleName: ESP26_SHRGB_01
Only On/Off works. Datapoints for color, brightness and sceneId are missing.
Thanks

**Comment by disaster123** [comment]
thx - please test latest github master and report back if it works.

Commit: https://github.com/disaster123/ioBroker.signifylights/commit/271ac41b260d839722e9dd01cf6715e12f0cfd77

**Comment by Burgruine** [comment]
Hallo, it works, all datapoints are available.
Thank you very much.
