### ISSUE TITLE
Fehler in den Einstellungen

### ISSUE THREAD

**Issue by hinzburner** [disaster123/ioBroker.signifylights#6]
Moin, 
großartig, dass ein Adapter für WiZ Leuchten im iobroker in Arbeit ist. Freut mich sehr.
Allerdings verstehe ich die Optionen in den Einstellungen der Instanz noch nicht. Im Protokoll ernte ich nur Fehlermeldungen, dass der Adapter unconfigured ist. Bind IP ist der iobroker? Oder der Router? 
Vielleicht wären Hinweise im readme toll, falls ich nicht der einzige sein sollte, der nicht weiter weiß. 

Besten Dank für deine Arbeit!

der sven

**Comment by disaster123** [comment]
Sorry bin gerade etwas Land unter.

bind ip ist die ip auf die der Adapter auf antworten und Updates der Lampen lauschen soll.
